name: WGBlockRestricter
main: com.mewin.WGBlockRestricter.WGBlockRestricterPlugin
description: WorldGuard extension to black/whitelist block types in specific regions.
version: 1.6.2
authors: [ mewin ]
depend: [ WorldGuard, WGCustomFlags ]

permissions:
  wgblockrestricter.ignore:
    default: op