name: WGBlockRestricter
main: com.mewin.WGBlockRestricter.WGBlockRestricterPlugin
description: WorldGuard extension to black/whitelist block types in specific regions.
version: 2.1
authors: [mewin, Borlea]
depend: [ WorldGuard, WGCustomFlags ]

permissions:
  wgblockrestricter.ignore:
    default: op